In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('international_financial_statistics_data.csv')
df

,oid,country_or_area,year,description,magnitude,value,category
0,79976ECZZF...,AFRICA N.S.,2009,COFFEE:UGANDA,US$ PER 100 LBS,77.127500,balance_of_payments_export_prices
1,79976ECDZF...,AFRICA N.S.,2009,COFFEE UGANDA (NEW YORK),INDEX NUMBER,144.519000,balance_of_payments_export_prices
2,79976ECZZF...,AFRICA N.S.,2008,COFFEE:UGANDA,US$ PER 100 LBS,106.240000,balance_of_payments_export_prices
3,79976ECDZF...,AFRICA N.S.,2008,COFFEE UGANDA (NEW YORK),INDEX NUMBER,199.069000,balance_of_payments_export_prices
4,79976ECZZF...,AFRICA N.S.,2007,COFFEE:UGANDA,US$ PER 100 LBS,88.298300,balance_of_payments_export_prices
...,...,...,...,...,...,...,...
884239,69862...ZF...,ZIMBABWE,1979,SHARE PRICE INDEX (INDUSTRIALS),INDEX NUMBER,0.000005,share_prices
884240,69862...ZF...,ZIMBABWE,1978,SHARE PRICE INDEX (INDUSTRIALS),INDEX NUMBER,0.000003,share_prices
884241,69862...ZF...,ZIMBABWE,1977,SHARE PRICE INDEX (INDUSTRIALS),INDEX NUMBER,0.000003,share_prices
884242,69862...ZF...,ZIMBABWE,1976,SHARE PRICE INDEX (INDUSTRIALS),INDEX NUMBER,0.000003,share_prices
884243,69862...ZF...,ZIMBABWE,1975,SHARE PRICE INDEX (INDUSTRIALS),INDEX NUMBER,0.000004,share_prices

In [4]:
print(df['country_or_area'].unique())

['AFRICA N.S.' 'ALGERIA' 'AUSTRALIA' 'AUSTRIA' 'BANGLADESH' 'BELGIUM'
 'BRAZIL' 'CANADA' 'CHILE' 'COLOMBIA' 'DENMARK' 'DJIBOUTI' 'EAST AFRICA'
 'ECUADOR' 'EMER.& DEVELOP. ECO.' 'FINLAND' 'FRANCE' 'GERMANY' 'GHANA'
 'GREECE' 'HUNGARY' 'INDONESIA' 'IRAN, I.R. OF' 'JAPAN'
 'KOREA, REPUBLIC OF' 'MALAYSIA' 'MAURITIUS' 'MOROCCO' 'NEW ZEALAND'
 'NIGERIA' 'NORWAY' 'OMAN' 'OTH CENT AMERICA NS' 'PERU' 'PHILIPPINES'
 'POLAND' 'PORTUGAL' 'RUSSIAN FEDERATION' 'SAUDI ARABIA' 'SINGAPORE'
 'SOUTH AFRICA' 'SPAIN' 'ST. LUCIA' 'SWEDEN' 'SWITZERLAND' 'THAILAND'
 'UKRAINE' 'UNITED ARAB EMIRATES' 'UNITED KINGDOM' 'UNITED STATES'
 'VENEZUELA, REP. BOL.' 'WORLD' 'ADVANCED ECONOMIES'
 'AFGHANISTAN, I.R. OF' 'AFRICA' 'ALBANIA' 'AMERICAN SAMOA' 'ANGOLA'
 'ANGUILLA' 'ANTIGUA AND BARBUDA' 'APEC' 'ARGENTINA' 'ARMENIA' 'ARUBA'
 'AZERBAIJAN, REP. OF' 'BAHAMAS, THE' 'BAHRAIN, KINGDOM OF' 'BARBADOS'
 'BELARUS' 'BELGIUM-LUXEMBOURG' 'BELIZE' 'BENIN' 'BERMUDA' 'BHUTAN'
 'BOLIVIA' 'BOSNIA & HERZEGOVINA' 'BOTSWANA' 'BRUNEI DARUSSALAM'
 'BULGARIA' 'BURKINA FASO' 'BURUNDI' 'CAMBODIA' 'CAMEROON' 'CAPE VERDE'
 'CENT. & EAST. EUROPE' 'CENTRAL AFRICAN REP.' 'CHAD'
 'CHINA,P.R.: MAINLAND' 'CHINA,P.R.:HONG KONG' 'CHINA,P.R.:MACAO'
 'CIS AND MONGOLIA' 'COMOROS' 'CONGO, DEM. REP. OF' 'CONGO, REPUBLIC OF'
 'COOK ISLANDS' 'COSTA RICA' 'COTE D IVOIRE' 'CROATIA' 'CYPRUS'
 'CZECH REPUBLIC' 'CZECHOSLOVAKIA' 'DEVELOPING ASIA' 'DOMINICA'
 'DOMINICAN REPUBLIC' 'EGYPT' 'EL SALVADOR' 'EQUATORIAL GUINEA' 'ESTONIA'
 'ETHIOPIA' 'EURO AREA' 'EUROPE' 'EXP. EARN.: NON-FUEL'
 'EXPORT EARN.: FUEL' 'FALKLAND ISLANDS' 'FAROE ISLANDS' 'FIJI'
 'FRENCH POLYNESIA' 'GABON' 'GAMBIA, THE' 'GEORGIA' 'GIBRALTAR'
 'GREENLAND' 'GRENADA' 'GUADELOUPE' 'GUAM' 'GUATEMALA' 'GUIANA, FRENCH'
 'GUINEA' 'GUINEA-BISSAU' 'GUYANA' 'HAITI' 'HONDURAS' 'ICELAND' 'INDIA'
 'IRAQ' 'IRELAND' 'ISRAEL' 'ITALY' 'JAMAICA' 'JORDAN' 'KAZAKHSTAN' 'KENYA'
 'KIRIBATI' 'KUWAIT' 'KYRGYZ REPUBLIC' 'LAO PEOPLE S DEM.REP' 'LATVIA'
 'LEBANON' 'LESOTHO' 'LIBERIA' 'LIBYA' 'LITHUANIA' 'LUXEMBOURG'
 'MACEDONIA, FYR' 'MADAGASCAR' 'MALAWI' 'MALDIVES' 'MALI' 'MALTA'
 'MARTINIQUE' 'MEXICO' 'MIDDLE EAST' 'MOLDOVA' 'MONGOLIA' 'MONTSERRAT'
 'MOZAMBIQUE' 'MYANMAR' 'NAMIBIA' 'NAURU' 'NEPAL' 'NETHERLANDS'
 'NETHERLANDS ANTILLES' 'NEW CALEDONIA' 'NICARAGUA' 'NIGER' 'PAKISTAN'
 'PANAMA' 'PANAMA CANAL ZONE' 'PAPUA NEW GUINEA' 'PARAGUAY' 'QATAR'
 'REUNION' 'ROMANIA' 'RWANDA' 'RYUKYUS' 'SAMOA' 'SAO TOME & PRINCIPE'
 'SENEGAL' 'SERBIA, REPUBLIC OF' 'SEYCHELLES' 'SIERRA LEONE'
 'SLOVAK REPUBLIC' 'SLOVENIA' 'SOLOMON ISLANDS' 'SRI LANKA' 'ST. HELENA'
 'ST. KITTS AND NEVIS' 'ST. PIERRE-MIQUELON' 'ST. VINCENT & GRENS.'
 'SUDAN' 'SURINAME' 'SWAZILAND' 'SYRIAN ARAB REPUBLIC' 'TAJIKISTAN'
 'TANZANIA' 'TIMOR' 'TOGO' 'TONGA' 'TRINIDAD AND TOBAGO' 'TUNISIA'
 'TURKEY' 'UGANDA' 'URUGUAY' 'VANUATU' 'VIETNAM' 'WESTERN HEMISPHERE'
 'YEMEN ARAB REP.' 'YEMEN, P.D. REP.' 'YEMEN, REPUBLIC OF'
 'YUGOSLAVIA, SFR' 'ZAMBIA' 'ZIMBABWE' 'CAYMAN ISLANDS' 'ECCU' 'ERITREA'
 'MAURITANIA' 'MONTENEGRO, REP. OF' 'SOMALIA' 'TURKMENISTAN'
 'WEST BANK AND GAZA' 'CEMAC' 'MICRONESIA, FED.STS.' 'SAN MARINO'
 'TIMOR-LESTE' 'WAEMU' 'ALL COUNTRIES' 'CEN.BANK WEST AFRICA' 'CUBA']